name: Set Outdooractive

on:
  workflow_dispatch:
    inputs:
        environment:    
            description: 'Environment'
            type: environment
            required: true

jobs:
  deploy:
      name: Set Attribut Outdooractive
      uses: ./.github/workflows/setAttributOutdooractive.yml
      with:
        environment: ${{ inputs.environment }}
