name: Set Outdooractive Ziggy

on:
  schedule:
  - cron: "0 19 * 1-12 6"

jobs:
  deploy:
    name: Set Attribut Outdooractive
    uses: ./.github/workflows/setAttributOutdooractive.yml
    with:
      variable_environment: ziggy
