name: Set Outdooractive Ziggy

on:
  workflow_dispatch: 
  schedule:
  - cron: "0 19 * 1-12 6"



jobs:
  build:
    runs-on: ubuntu-latest
    environment: ziggy
    env:
      AKENEO_HOST: ${{ secrets.AKENEO_HOST }}
      AKENEO_CLIENT_ID: ${{ secrets.AKENEO_CLIENT_ID }}
      AKENEO_CLIENT_SECRET: ${{ secrets.AKENEO_CLIENT_SECRET }}
      AKENEO_USERNAME: ${{ secrets.AKENEO_USERNAME }}
      AKENEO_PASSWORD: ${{ secrets.AKENEO_PASSWORD }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_EXPORT_PATH: ${{ secrets.S3_EXPORT_PATH }}
      CDN_ENDPOINT: ${{ secrets.CDN_ENDPOINT }}
      OUTDOORACTIVE_KEY: ${{ secrets.OUTDOORACTIVE_KEY }}
      OUTDOORACTIVE_SOURCE: ${{ secrets.OUTDOORACTIVE_SOURCE }}
      OUTDOORACTIVE_OWNER: ${{ secrets.OUTDOORACTIVE_OWNER }}
      OUTDOORACTIVE_OWNERNAME: ${{ secrets.OUTDOORACTIVE_OWNERNAME }}

  deploy:
    name: Set Attribut Outdooractive
    uses: ./.github/workflows/setAttributOutdooractive.yml
    with:
      variable_environment: ziggy
